# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
