# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20170210_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.IntegerField(),
        ),
    ]
