# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20170215_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=70)),
                ('detail', models.CharField(max_length=500)),
                ('value', models.FloatField(default=0)),
                ('list_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Type_programe')),
                ('pass_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Pass_book')),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='pass_book',
        ),
        migrations.RemoveField(
            model_name='program',
            name='type_programe',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
