# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
    ]
