# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
