# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_list_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='imported_csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('csv_file', models.FileField(upload_to='accounting/media/imported_csv/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
