# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_imported_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='imported_csv',
            name='pass_book',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounting.Pass_book'),
        ),
    ]
